version: '3'
services:
    mkadiri-java-microservice:
        image: mkadiri/java-microservice
        container_name: mkadiri-java-microservice
        ports:
            - 8181:8080
        environment:
            - MYSQL_HOST=mkadiri-mysql
            - MYSQL_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=mkadiri_java_microservice
        restart: always
    mkadiri-mysql:
        image: mysql
        container_name: mkadiri-mysql
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
        command: --default-authentication-plugin=mysql_native_password
        restart: always
